services:
  database:
    image: postgres
    restart: always
    container_name: ${APP_NAME}_database
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    env_file: .env
    volumes:
      - data:/var/lib/postgresql/data

  app:
    image: stiv1100001/sIDP
    container_name: ${APP_NAME}_app
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    volumes:
      - .:/usr/src/app
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    restart: always

volumes:
  data:
